export type NasdaqSymbol = {
  name: string
  symbol: string
  yahooFinanceSymbol?: string
  exchange: string
  type?: string
  url?: string
  lists?: string[]
  tradableAt?: string[]
  region: "US" | "BR" | "AU" | "CA" | "FR" | "DE" | "HK" | "IN" | "IT" | "ES" | "GB" | "SG"
}

export const miners: NasdaqSymbol[] = [
  {
    symbol: "WULF",
    name: "TeraWulf Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/WULF",
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "SATO",
    yahooFinanceSymbol: "SATO.V",
    name: "Sato Technologies Corp.",
    exchange: "TSXV",
    url: "https://finance.yahoo.com/quote/SATO.V",
    lists: ["ap"],
    type: "Hosted Mining,High-Performance Computing,Artificial Intelligence",
    region: "CA",
  },
  {
    symbol: "CBTTF",
    name: "Cathedra Bitcoin Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/CBTTF",
    type: "Prop Mining",
    region: "US",
  },
  // {
  //   symbol: "CBIT",
  //   name: "Cathedra Bitcoin Inc",
  //   exchange: "TSVX",
  //   url: "https://finance.yahoo.com/quote/CBTTF",
  //   type: "Prop Mining",
  //   region: "CA",
  // },
  {
    symbol: "BTCM",
    name: "BIT Mining Ltd",
    exchange: "NYSE",
    url: "https://finance.yahoo.com/quote/BTCM",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "CIFR",
    name: "Cipher Mining Inc.",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/CIFR",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "BLQC",
    name: "BlockQuarry Corp.",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/BLQC",
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "BITF",
    name: "Bitfarms Ltd.",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/BITF",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "MARA",
    name: "Marathon Patent Group Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/MARA",
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "HUT",
    name: "Hut 8 Mining Corp.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/HUT",
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "GREE",
    name: "Greenidge",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/GREE",
    type: "Diversified",
    lists: ["ap"],
    region: "US",
  },
  {
    symbol: "SDIG",
    name: "Stronghold Digital Mining Inc",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/SDIG",
    type: "Hosted Mining",
    lists: ["ap"],
    region: "US",
  },
  {
    symbol: "HIVE",
    name: "VHIVE Blockchain Technologies Ltd",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/HIVE",
    type: "Prop Mining",
    region: "CA",
  },
  {
    symbol: "DGHI",
    name: "Digihost Technology Inc",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/DGHI",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "CLSK",
    name: "CleanSpark Inc",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/CLSK",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "ANY",
    name: "Sphere 3D Corp",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/ANY",
    tradableAt: ["boom"],
    type: "Diversified",
    region: "US",
  },
  {
    symbol: "IREN",
    name: "Iris Energy Ltd",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/IREN",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "ARBK",
    name: "Argo Blockchain Plc",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/ARBK",
    tradableAt: ["boom"],
    region: "US",
  },
  {
    symbol: "CORZQ",
    name: "Core Scientific, Inc.",
    exchange: "OTC",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/CORZQ",
    type: "Diversified",
    region: "US",
  },
  {
    symbol: "MGTI",
    name: "MGT Capital Investments Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/MGTI",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "BTZI",
    name: "BOTS Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/BTZI",
    tradableAt: ["boom"],
    type: "Diversified",
    region: "US",
  },
  {
    symbol: "WELX",
    name: "Winland Holdings Corp",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/WELX",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "CSTR",
    name: "CryptoStar Corp.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/CSTR",
    tradableAt: ["boom"],
    type: "Prop Mining and Hosting",
    region: "US",
  },
  {
    symbol: "INTV",
    name: "Integrated Ventures Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/INTV",
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "INVU",
    name: "Investview Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/INVU",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "MIGI",
    name: "Mawson Infrastructure Group Inc",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/MIGI",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "CCTL",
    name: "Coin Citadel",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/CCTL",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "EBON",
    name: "Ebang International Holdings, Inc.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/EBON",
    tradableAt: ["boom"],
    type: "Manufacturer",
    region: "US",
  },
  {
    symbol: "CBTC",
    name: "XTRA Bitcoin Inc.",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/CBTC",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "RIOT",
    name: "Riot Blockchain, Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/RIOT",
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "DMGI",
    yahooFinanceSymbol: "DMGI.V",
    name: "DMG Blockchain Solutions",
    exchange: "TSXV",
    url: "https://finance.yahoo.com/quote/DMGI",
    type: "Prop Mining and Hosting",
    lists: ["ap"],
    region: "CA",
  },
  {
    symbol: "NB2",
    yahooFinanceSymbol: "NB2.DE",
    name: "Northern Data AG",
    exchange: "XETR",
    url: "https://finance.yahoo.com/quote/NB2",
    tradableAt: ["boom"],
    type: "Prop Mining and Hosting",
    region: "DE",
  },
  {
    symbol: "BFCH",
    name: "BitFrontier Capital Holdings Inc.",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/BFCH",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    region: "US",
  },
  {
    symbol: "SOS",
    name: "SOS Limited",
    exchange: "NYSE",
    url: "https://finance.yahoo.com/quote/SOS",
    tradableAt: ["boom"],
    type: "Diversified",
    region: "US",
  },
  {
    symbol: "SASR",
    name: "Sandy Spring Bancorp",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/SASR",
    tradableAt: ["boom"],
    type: "Prop Mining",
    region: "US",
  },
  {
    symbol: "CAN",
    name: "Canaan, Inc.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/CAN",
    tradableAt: ["boom"],
    type: "Manufacturer",
    region: "US",
  },
  // {
  //   symbol: "LEAS",
  //   name: "Strategic Asset Leasing Inc.",
  //   exchange: "OTC",
  //   url: "https://finance.yahoo.com/quote/LEAS",
  //   tradableAt: ["boom"],
  //   type: "Prop Mining",
  //   region: "US",
  // },
  {
    symbol: "BTBT",
    name: "Bit Digital Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/BTBT",
    type: "Hosted Mining and AI",
    region: "US",
  },
  {
    symbol: "WGMI",
    name: "Valkyrie Bitcoin Miners ETF",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/WGMI",
    type: "ETF",
    region: "US",
  },
  {
    symbol: "BITQ",
    name: "Bitwise Crypto Industry Innovators ETF",
    exchange: "AMEX",
    url: "https://finance.yahoo.com/quote/BITQ",
    type: "ETF",
    region: "US",
  },
  {
    symbol: "DAPP",
    name: "VanEck Digital Transformation ETF",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/DAPP",
    type: "ETF",
    region: "US",
  },
  {
    symbol: "BKCH",
    name: "Global X Blockchain ETF",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/BKCH",
    type: "ETF",
    region: "US",
  },
  {
    symbol: "BTDR",
    name: "Bitdeer Technologies Group",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/BTDR",
    tradableAt: ["boom"],
    lists: ["ap"],
    region: "US",
  },
  {
    symbol: "SLNH",
    name: "Soluna Holdings, Inc.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/SLNH",
    tradableAt: ["boom"],
    lists: ["ap"],
    region: "US",
  },
  // {
  //   symbol: "PHX",
  //   name: "Phoenix Group Plc",
  //   exchange: "ADX",
  //   url: "https://www.tradingview.com/symbols/ADX-PHX/",
  //   tradableAt: [],
  //   lists: [],
  // },
]
// const ai: NasdaqSymbol[] = [
//   {
//     symbol: "METV",
//     name: "MRoundhill Ball Metaverse ETF",
//     exchange: "NYSE",
//     url: "https://finance.yahoo.com/quote/METV",
//   },
//   {
//     symbol: "TECB",
//     name: "iShares U.S. Tech Breakthrough Multisector ETF",
//     exchange: "NYSE",
//     url: "https://finance.yahoo.com/quote/TECB",
//   },
//   {
//     symbol: "AIQ",
//     name: "Global X Artificial Intelligence & Technology ETF",
//     exchange: "NASDAQ",
//     url: "https://finance.yahoo.com/quote/AIQ",
//   },
//   {
//     symbol: "BOTZ",
//     name: "Global X Robotics & Artificial Intelligence ETF",
//     exchange: "NASDAQ",
//     url: "https://finance.yahoo.com/quote/BOTZ",
//   },
//   {
//     symbol: "ROBT",
//     name: "First Trust Nasdaq Artificial Intelligence and Robotics ETF",
//     exchange: "NASDAQ",
//     url: "https://finance.yahoo.com/quote/ROBT",
//   },
//   {
//     symbol: "PNQI",
//     name: "Invesco NASDAQ Internet ETF",
//     exchange: "NASDAQ",
//     url: "https://finance.yahoo.com/quote/PNQI",
//   },
//   {
//     symbol: "QQQ",
//     name: "Invesco QQQ Trust",
//     exchange: "NASDAQ",
//     url: "https://finance.yahoo.com/quote/QQQ",
//   },
//   {
//     symbol: "LOUP",
//     name: "Innovator Deepwater Frontier Tech ETF",
//     exchange: "NYSE",
//     url: "https://finance.yahoo.com/quote/LOUP",
//   },
//   {
//     symbol: "IXN",
//     name: "iShares Global Tech ETF",
//     exchange: "NYSE",
//     url: "https://finance.yahoo.com/quote/IXN",
//   },
//   {
//     symbol: "IYW",
//     name: "iShares U.S. Technology ETF",
//     exchange: "NYSE",
//     url: "https://finance.yahoo.com/quote/IYW",
//   },
//   {
//     symbol: "XLK",
//     name: "Technology Select Sector SPDR Fund",
//     exchange: "NYSE",
//     url: "https://finance.yahoo.com/quote/XLK",
//   },
// ]
