export type NasdaqSymbol = {
  name: string
  symbol: string
  yahooFinanceSymbol?: string
  exchange: string
  type?: string
  url?: string
  lists?: string[]
  tradableAt?: string[]
  region: "US" | "BR" | "AU" | "CA" | "FR" | "DE" | "HK" | "IN" | "IT" | "ES" | "GB" | "SG"
  etfs: string[]
  holders?: string[]
  notes?: string[]
}

export const miners: NasdaqSymbol[] = [
  {
    symbol: "WULF",
    name: "TeraWulf Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/WULF",
    type: "Hosted Mining",
    etfs: [],
    region: "US",
    notes: [
      "Bearish post halving: https://twitter.com/CK_Cryptoklepto/status/1743060713264816194?t=BFGRAb4FSLu4n1X25amy8A",
      "Bearish post halving: https://twitter.com/Micro2Macr0/status/1743093231082955261?t=BFGRAb4FSLu4n1X25amy8A",
    ],
  },
  {
    symbol: "SATO",
    yahooFinanceSymbol: "SATO.V",
    name: "Sato Technologies Corp.",
    exchange: "TSXV",
    url: "https://finance.yahoo.com/quote/SATO.V",
    lists: ["ap"],
    type: "Hosted Mining,High-Performance Computing,Artificial Intelligence",
    etfs: [],
    region: "CA",
  },
  {
    symbol: "CBIT",
    yahooFinanceSymbol: "CBIT.V",
    name: "Cathedra Bitcoin Inc",
    exchange: "TSXV",
    url: "https://finance.yahoo.com/quote/CBTTF",
    type: "Prop Mining",
    etfs: [],
    region: "CA",
  },
  {
    symbol: "BTCM",
    name: "BIT Mining Ltd",
    exchange: "NYSE",
    url: "https://finance.yahoo.com/quote/BTCM",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "CIFR",
    name: "Cipher Mining Inc.",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/CIFR",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: ["WGMI"],
    region: "US",
    holders: ["ia"],
  },
  {
    symbol: "BLQC",
    name: "BlockQuarry Corp.",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/BLQC",
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "BITF",
    name: "Bitfarms Ltd.",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/BITF",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: ["BITQ", "BKCH", "WGMI", "DAPP"],
    region: "US",
    holders: ["ia"],
  },
  {
    symbol: "MARA",
    name: "Marathon Patent Group Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/MARA",
    type: "Hosted Mining",
    etfs: ["BITQ", "BKCH", "WGMI", "DAPP"],
    region: "US",
  },
  {
    symbol: "HUT",
    name: "Hut 8 Mining Corp.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/HUT",
    type: "Prop Mining",
    etfs: ["BITQ", "BKCH", "WGMI"],
    region: "US",
  },
  {
    symbol: "GREE",
    name: "Greenidge",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/GREE",
    type: "Diversified",
    lists: ["ap"],
    etfs: [],
    region: "US",
  },
  {
    symbol: "SDIG",
    name: "Stronghold Digital Mining Inc",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/SDIG",
    type: "Hosted Mining",
    lists: ["ap"],
    etfs: [],
    region: "US",
    notes: ["Bearish post halving: https://twitter.com/CK_Cryptoklepto/status/1743060713264816194?t=BFGRAb4FSLu4n1X25amy8A"],
  },
  {
    symbol: "HIVE",
    name: "VHIVE Blockchain Technologies Ltd",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/HIVE",
    type: "Prop Mining",
    etfs: ["WGMI"],
    region: "CA",
  },
  {
    symbol: "DGHI",
    name: "Digihost Technology Inc",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/DGHI",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "CLSK",
    name: "CleanSpark Inc",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/CLSK",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: ["BKCH", "WGMI", "DAPP"],
    region: "US",
    holders: ["ia"],
  },
  {
    symbol: "ANY",
    name: "Sphere 3D Corp",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/ANY",
    tradableAt: ["boom"],
    type: "Diversified",
    etfs: [],
    region: "US",
    notes: ["Bearish post halving: https://twitter.com/CK_Cryptoklepto/status/1743060713264816194?t=BFGRAb4FSLu4n1X25amy8A"],
  },
  {
    symbol: "IREN",
    name: "Iris Energy Ltd",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/IREN",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: ["BKCH", "WGMI", "DAPP"],
    region: "US",
  },
  {
    symbol: "ARBK",
    name: "Argo Blockchain Plc",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/ARBK",
    tradableAt: ["boom"],
    etfs: [],
    region: "US",
  },
  {
    symbol: "CORZQ",
    name: "Core Scientific, Inc.",
    exchange: "OTC",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/CORZQ",
    type: "Diversified",
    etfs: [],
    region: "US",
  },
  {
    symbol: "MGTI",
    name: "MGT Capital Investments Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/MGTI",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "BTZI",
    name: "BOTS Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/BTZI",
    tradableAt: ["boom"],
    type: "Diversified",
    etfs: [],
    region: "US",
  },
  {
    symbol: "WELX",
    name: "Winland Holdings Corp",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/WELX",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "CSTR",
    name: "CryptoStar Corp.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/CSTR",
    tradableAt: ["boom"],
    type: "Prop Mining and Hosting",
    etfs: [],
    region: "US",
  },
  {
    symbol: "INTV",
    name: "Integrated Ventures Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/INTV",
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "INVU",
    name: "Investview Inc",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/INVU",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "MIGI",
    name: "Mawson Infrastructure Group Inc",
    exchange: "NASDAQ",
    lists: ["ia"],
    url: "https://finance.yahoo.com/quote/MIGI",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: [],
    region: "US",
    notes: ["Bearish post halving: https://twitter.com/CK_Cryptoklepto/status/1743060713264816194?t=BFGRAb4FSLu4n1X25amy8A"],
  },
  {
    symbol: "CCTL",
    name: "Coin Citadel",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/CCTL",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "EBON",
    name: "Ebang International Holdings, Inc.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/EBON",
    tradableAt: ["boom"],
    type: "Manufacturer",
    etfs: [],
    region: "US",
  },
  {
    symbol: "CBTC",
    name: "XTRA Bitcoin Inc.",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/CBTC",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "RIOT",
    name: "Riot Blockchain, Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/RIOT",
    type: "Hosted Mining",
    etfs: ["BITQ", "BKCH", "WGMI", "DAPP"],
    region: "US",
    holders: ["ia"],
  },
  {
    symbol: "DMGI",
    yahooFinanceSymbol: "DMGI.V",
    name: "DMG Blockchain Solutions",
    exchange: "TSXV",
    url: "https://finance.yahoo.com/quote/DMGI",
    type: "Prop Mining and Hosting",
    lists: ["ap"],
    etfs: [],
    region: "CA",
  },
  {
    symbol: "NB2",
    yahooFinanceSymbol: "NB2.DE",
    name: "Northern Data AG",
    exchange: "XETR",
    url: "https://finance.yahoo.com/quote/NB2",
    tradableAt: ["boom"],
    type: "Prop Mining and Hosting",
    etfs: ["BITQ", "DAPP"],
    region: "DE",
  },
  {
    symbol: "BFCH",
    name: "BitFrontier Capital Holdings Inc.",
    exchange: "OTC",
    url: "https://finance.yahoo.com/quote/BFCH",
    tradableAt: ["boom"],
    type: "Hosted Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "SOS",
    name: "SOS Limited",
    exchange: "NYSE",
    url: "https://finance.yahoo.com/quote/SOS",
    tradableAt: ["boom"],
    type: "Diversified",
    etfs: [],
    region: "US",
  },
  {
    symbol: "SASR",
    name: "Sandy Spring Bancorp",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/SASR",
    tradableAt: ["boom"],
    type: "Prop Mining",
    etfs: [],
    region: "US",
  },
  {
    symbol: "CAN",
    name: "Canaan, Inc.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/CAN",
    tradableAt: ["boom"],
    type: "Manufacturer",
    etfs: [],
    region: "US",
  },
  {
    symbol: "BTBT",
    name: "Bit Digital Inc.",
    exchange: "NASDAQ",
    lists: ["ia", "ap"],
    url: "https://finance.yahoo.com/quote/BTBT",
    type: "Hosted Mining and AI",
    etfs: ["BKCH", "WGMI"],
    region: "US",
  },
  {
    symbol: "WGMI",
    name: "Valkyrie Bitcoin Miners ETF",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/WGMI",
    type: "ETF",
    etfs: [],
    region: "US",
  },
  {
    symbol: "BITQ",
    name: "Bitwise Crypto Industry Innovators ETF",
    exchange: "AMEX",
    url: "https://finance.yahoo.com/quote/BITQ",
    type: "ETF",
    etfs: [],
    region: "US",
  },
  {
    symbol: "DAPP",
    name: "VanEck Digital Transformation ETF",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/DAPP",
    type: "ETF",
    etfs: [],
    region: "US",
  },
  {
    symbol: "BKCH",
    name: "Global X Blockchain ETF",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/BKCH",
    type: "ETF",
    etfs: [],
    region: "US",
  },
  {
    symbol: "BTDR",
    name: "Bitdeer Technologies Group",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/BTDR",
    tradableAt: ["boom"],
    lists: ["ap"],
    etfs: [],
    region: "US",
  },
  {
    symbol: "SLNH",
    name: "Soluna Holdings, Inc.",
    exchange: "NASDAQ",
    url: "https://finance.yahoo.com/quote/SLNH",
    tradableAt: ["boom"],
    lists: ["ap"],
    etfs: [],
    region: "US",
  },
]
