type NasdaqSymbol = {
  name: string
  symbol: string
  exchange: string
}

export const miners: NasdaqSymbol[] = [
  { symbol: "WULF", name: "TeraWulf Inc.", exchange: "NASDAQ" },
  { symbol: "CBTTF", name: "Cathedra Bitcoin Inc", exchange: "OTC" },
  { symbol: "BTCM", name: "BIT Mining Ltd", exchange: "NYSE" },
  { symbol: "SGLY", name: "Sino-Global Shipping America Ltd", exchange: "NASDAQ" },
  { symbol: "CIFR", name: "Cipher Mining Inc.", exchange: "NASDAQ" },
  { symbol: "BLQC", name: "BlockQuarry Corp.", exchange: "OTC" },
  { symbol: "BITF", name: "Bitfarms Ltd.", exchange: "NASDAQ" },
  { symbol: "MARA", name: "Marathon Patent Group Inc.", exchange: "NASDAQ" },
  { symbol: "HUT", name: "Hut 8 Mining Corp.", exchange: "NASDAQ" },
  { symbol: "GREE", name: "Greenidge", exchange: "NASDAQ" },
  { symbol: "SDIG", name: "Stronghold Digital Mining Inc", exchange: "NASDAQ" },
  { symbol: "HIVE", name: "VHIVE Blockchain Technologies Ltd", exchange: "NASDAQ" },
  { symbol: "DGHI", name: "Digihost Technology Inc", exchange: "NASDAQ" },
  { symbol: "CLSK", name: "CleanSpark Inc", exchange: "NASDAQ" },
  { symbol: "ANY", name: "Sphere 3D Corp", exchange: "NASDAQ" },
  // { symbol: "LGLOF", name: "Link Global Technologies Inc." , exchange: 'NASDAQ'},
  { symbol: "IREN", name: "Iris Energy Ltd", exchange: "NASDAQ" },
  { symbol: "ARBK", name: "Argo Blockchain Plc", exchange: "NASDAQ" },
  { symbol: "CORZQ", name: "Core Scientific, Inc.", exchange: "OTC" },
  { symbol: "MGTI", name: "MGT Capital Investments Inc", exchange: "OTC" },
  { symbol: "BTZI", name: "BOTS Inc", exchange: "OTC" },
  // { symbol: "TAALF", name: "Taal Distributed Information Technologies, Inc" , exchange: 'NASDAQ'},
  { symbol: "WELX", name: "Winland Holdings Corp", exchange: "OTC" },
  // { symbol: "RIGZ", name: "Viridi Funds" , exchange: 'NASDAQ'},
  { symbol: "CSTR", name: "CryptoStar Corp.", exchange: "NASDAQ" },
  { symbol: "INTV", name: "Integrated Ventures Inc", exchange: "OTC" },
  { symbol: "INVU", name: "Investview Inc", exchange: "OTC" },
  { symbol: "MIGI", name: "Mawson Infrastructure Group Inc", exchange: "NASDAQ" },
  { symbol: "CCTL", name: "Coin Citadel", exchange: "OTC" },
  { symbol: "EBON", name: "Ebang International Holdings, Inc.", exchange: "NASDAQ" },
  { symbol: "CBTC", name: "XTRA Bitcoin Inc.", exchange: "OTC" },
  { symbol: "RIOT", name: "Riot Blockchain, Inc.", exchange: "NASDAQ" },
  // { symbol: "DMGI", name: "DMG Blockchain Solutions" , exchange: 'NASDAQ'},
  // { symbol: "NB2", name: "Northern Data AG" , exchange: 'NASDAQ'},
  { symbol: "BFCH", name: "BitFrontier Capital Holdings Inc.", exchange: "OTC" },
  { symbol: "SOS", name: "SOS Limited", exchange: "NYSE" },
  { symbol: "SASR", name: "Sandy Spring Bancorp", exchange: "NASDAQ" },
  { symbol: "CAN", name: "Canaan, Inc.", exchange: "NASDAQ" },
  { symbol: "LEAS", name: "Strategic Asset Leasing Inc.", exchange: "OTC" },
  { symbol: "HUT", name: "THut 8 Mining Corp.", exchange: "NASDAQ" },
  { symbol: "BTBT", name: "Bit Digital Inc.", exchange: "NASDAQ" },
  { symbol: "SATO", name: "Sato Technologies Corp.", exchange: "TSXV" },
  { symbol: "WGMI", name: "Valkyrie Bitcoin Miners EFT", exchange: "NASDAQ" },
]
